image: Visual Studio 2015   

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\sbe2comms
shallow_clone: true             

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14

install:
    - call appveyor_install.bat
    - ps: (new-object net.webclient).DownloadFile('http://xmlsoft.org/sources/win32/libxml2-2.7.8.win32.zip', 'C:\libxml2.zip')
    - ps: Expand-Archive C:\libxml2.zip -DestinationPath C:\libxml2

build_script:
    - mkdir build.%PLATFORM%.%CONFIGURATION%
    - cd build.%PLATFORM%.%CONFIGURATION%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DBOOST_ROOT="C:\Libraries\boost_1_59_0" -DLIBXML2_INCLUDE_DIR="C:/libxml2/include" -DLIBXML2_LIBRARIES="C:/libxml2/lib
    - nmake install

 


