language: cpp
sudo: true
notifications:
  email: false

matrix:
  include:
    - os: linux
      env: _CC=gcc-4.8 _CXX=g++-4.8 _BUILD="-DCC_COMMS_LIB_ONLY=ON"
    - os: linux
      env: _CC=gcc-4.8 _CXX=g++-4.8 _BUILD="-DCC_COMMS_LIB_ONLY=ON -DCMAKE_BUILD_TYPE=Release"
    - os: linux
      env: _CC=gcc-4.8 _CXX=g++-4.8 _BUILD="-DCC_COMMS_LIB_ONLY=ON -DCMAKE_BUILD_TYPE=MinSizeRel"
    - os: linux
      env: _CC=gcc-4.9 _CXX=g++-4.9 
    - os: linux
      env: _CC=gcc-4.9 _CXX=g++-4.9 _BUILD="-DCMAKE_BUILD_TYPE=Release"
    - os: linux
      env: _CC=gcc-4.9 _CXX=g++-4.9 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel"      
    - os: linux
      env: _CC=gcc-5 _CXX=g++-5
    - os: linux
      env: _CC=gcc-5 _CXX=g++-5 _BUILD=-DCMAKE_BUILD_TYPE=Release
    - os: linux
      env: _CC=gcc-5 _CXX=g++-5 _BUILD=-DCMAKE_BUILD_TYPE=MinSizeRel    
    - os: linux
      env: _CC=gcc-5 _CXX=g++-5 _BUILD=-DCMAKE_CXX_STANDARD=14
    - os: linux
      env: _CC=gcc-5 _CXX=g++-5 _BUILD="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14"
    - os: linux
      env: _CC=gcc-5 _CXX=g++-5 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_STANDARD=14"     
    - os: linux
      env: _CC=gcc-6 _CXX=g++-6
    - os: linux
      env: _CC=gcc-6 _CXX=g++-6 _BUILD=-DCMAKE_BUILD_TYPE=Release
    - os: linux
      env: _CC=gcc-6 _CXX=g++-6 _BUILD=-DCMAKE_BUILD_TYPE=MinSizeRel          
    - os: linux
      env: _CC=clang-3.9 _CXX=clang++-3.9 
    - os: linux
      env: _CC=clang-3.9 _CXX=clang++-3.9 _BUILD="-DCMAKE_BUILD_TYPE=Release"
    - os: linux
      env: _CC=clang-3.9 _CXX=clang++-3.9 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel"
    - os: linux
      env: _CC=clang-3.9 _CXX=clang++-3.9 _BUILD=-DCMAKE_CXX_STANDARD=14
    - os: linux
      env: _CC=clang-3.9 _CXX=clang++-3.9 _BUILD="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14"
    - os: linux
      env: _CC=clang-3.9 _CXX=clang++-3.9 _BUILD="-DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_CXX_STANDARD=14"
      
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.9 main" -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.9 g++-5 g++-6 clang-3.9 cmake cmake-data libxml2-dev libboost-all-dev -y      

before_script:
  - mkdir build
  - cd build
  - CC=${_CC} CXX=${_CXX} cmake .. ${_BUILD}

script:
  - VERBOSE=1 make install

