//
// Copyright 2017 (C). Alex Robenko. All rights reserved.
//

// This code is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "Doxygen.h"

#include <iostream>
#include <fstream>
//#include <algorithm>

#include <boost/filesystem.hpp>
#include <boost/algorithm/string.hpp>

#include "common.h"
#include "output.h"
#include "DB.h"
#include "log.h"

namespace bf = boost::filesystem;
namespace ba = boost::algorithm;

namespace sbe2comms
{

namespace
{
const std::string DocDirName("doc");
} // namespace

Doxygen::Doxygen(DB& db)
  : m_db(db),
    m_name(db.getPackageName())
{
    ba::replace_all(m_name, " ", "_");
}

bool Doxygen::write()
{
    boost::system::error_code ec;
    auto dir = bf::path(m_db.getRootPath()) / DocDirName;
    bf::create_directories(dir, ec);
    if (ec) {
        log::error() << "Failed to create \"" << dir.string() <<
                "\" with error \"" << ec.message() << "\"!" << std::endl;
        return false;
    }


    return writeLayout() && writeConf() && writeNamespaces() && writeMain();
}

bool Doxygen::writeLayout()
{
    auto relPath = DocDirName + '/' + "layout.xml";
    auto filePath = bf::path(m_db.getRootPath()) / relPath;
    log::info() << "Generating " << relPath << std::endl;
    std::ofstream out(filePath.string());
    if (!out) {
        log::error() << "Failed to create " << filePath.string() << std::endl;
        return false;
    }

    out << "<doxygenlayout version=\"1.0\">\n" <<
           "  <navindex>\n"
           "    <tab type=\"mainpage\" visible=\"yes\" title=\"\"/>\n"
           "    <tab type=\"pages\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "    <tab type=\"modules\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "    <tab type=\"namespaces\" visible=\"yes\" title=\"\">\n"
           "      <tab type=\"namespacelist\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "      <tab type=\"namespacemembers\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "    </tab>\n"
           "    <tab type=\"classes\" visible=\"yes\" title=\"\">\n"
           "      <tab type=\"classlist\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "      <tab type=\"classindex\" visible=\"$ALPHABETICAL_INDEX\" title=\"\"/>\n"
           "      <tab type=\"hierarchy\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "      <tab type=\"classmembers\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "    </tab>\n"
           "    <tab type=\"files\" visible=\"yes\" title=\"\">\n"
           "      <tab type=\"filelist\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "      <tab type=\"globals\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "    </tab>\n"
           "    <tab type=\"examples\" visible=\"yes\" title=\"\" intro=\"\"/>\n"
           "  </navindex>\n\n"
           "  <!-- Layout definition for a class page -->\n"
           "  <class>\n"
           "    <includes visible=\"$SHOW_INCLUDE_FILES\"/>\n"
           "    <briefdescription visible=\"no\"/>\n"
           "    <detaileddescription title=\"\"/>\n"
           "    <inheritancegraph visible=\"$CLASS_GRAPH\"/>\n"
           "    <collaborationgraph visible=\"$COLLABORATION_GRAPH\"/>\n"
           "    <memberdecl>\n"
           "      <nestedclasses visible=\"yes\" title=\"\"/>\n"
           "      <publictypes title=\"\"/>\n"
           "      <services title=\"\"/>\n"
           "      <interfaces title=\"\"/>\n"
           "      <publicslots title=\"\"/>\n"
           "      <signals title=\"\"/>\n"
           "      <publicmethods title=\"\"/>\n"
           "      <publicstaticmethods title=\"\"/>\n"
           "      <publicattributes title=\"\"/>\n"
           "      <publicstaticattributes title=\"\"/>\n"
           "      <protectedtypes title=\"\"/>\n"
           "      <protectedslots title=\"\"/>\n"
           "      <protectedmethods title=\"\"/>\n"
           "      <protectedstaticmethods title=\"\"/>\n"
           "      <protectedattributes title=\"\"/>\n"
           "      <protectedstaticattributes title=\"\"/>\n"
           "      <packagetypes title=\"\"/>\n"
           "      <packagemethods title=\"\"/>\n"
           "      <packagestaticmethods title=\"\"/>\n"
           "      <packageattributes title=\"\"/>\n"
           "      <packagestaticattributes title=\"\"/>\n"
           "      <properties title=\"\"/>\n"
           "      <events title=\"\"/>\n"
           "      <privatetypes title=\"\"/>\n"
           "      <privateslots title=\"\"/>\n"
           "      <privatemethods title=\"\"/>\n"
           "      <privatestaticmethods title=\"\"/>\n"
           "      <privateattributes title=\"\"/>\n"
           "      <privatestaticattributes title=\"\"/>\n"
           "      <friends title=\"\"/>\n"
           "      <related title=\"\" subtitle=\"\"/>\n"
           "      <membergroups visible=\"yes\"/>\n"
           "    </memberdecl>\n"
           "    <memberdef>\n"
           "      <inlineclasses title=\"\"/>\n"
           "      <typedefs title=\"\"/>\n"
           "      <enums title=\"\"/>\n"
           "      <services title=\"\"/>\n"
           "      <interfaces title=\"\"/>\n"
           "      <constructors title=\"\"/>\n"
           "      <functions title=\"\"/>\n"
           "      <related title=\"\"/>\n"
           "      <variables title=\"\"/>\n"
           "      <properties title=\"\"/>\n"
           "      <events title=\"\"/>\n"
           "    </memberdef>\n"
           "    <allmemberslink visible=\"yes\"/>\n"
           "    <usedfiles visible=\"$SHOW_USED_FILES\"/>\n"
           "    <authorsection visible=\"yes\"/>\n"
           "  </class>\n\n"
           "  <namespace>\n"
           "    <briefdescription visible=\"yes\"/>\n"
           "    <memberdecl>\n"
           "      <nestednamespaces visible=\"yes\" title=\"\"/>\n"
           "      <constantgroups visible=\"yes\" title=\"\"/>\n"
           "      <classes visible=\"yes\" title=\"\"/>\n"
           "      <typedefs title=\"\"/>\n"
           "      <enums title=\"\"/>\n"
           "      <functions title=\"\"/>\n"
           "      <variables title=\"\"/>\n"
           "      <membergroups visible=\"yes\"/>\n"
           "    </memberdecl>\n"
           "    <detaileddescription title=\"\"/>\n"
           "    <memberdef>\n"
           "      <inlineclasses title=\"\"/>\n"
           "      <typedefs title=\"\"/>\n"
           "      <enums title=\"\"/>\n"
           "      <functions title=\"\"/>\n"
           "      <variables title=\"\"/>\n"
           "    </memberdef>\n"
           "    <authorsection visible=\"yes\"/>\n"
           "  </namespace>\n\n"
           "  <file>\n"
           "    <briefdescription visible=\"yes\"/>\n"
           "    <includes visible=\"$SHOW_INCLUDE_FILES\"/>\n"
           "    <includegraph visible=\"$INCLUDE_GRAPH\"/>\n"
           "    <includedbygraph visible=\"$INCLUDED_BY_GRAPH\"/>\n"
           "    <sourcelink visible=\"yes\"/>\n"
           "    <memberdecl>\n"
           "      <classes visible=\"yes\" title=\"\"/>\n"
           "      <namespaces visible=\"yes\" title=\"\"/>\n"
           "      <constantgroups visible=\"yes\" title=\"\"/>\n"
           "      <defines title=\"\"/>\n"
           "      <typedefs title=\"\"/>\n"
           "      <enums title=\"\"/>\n"
           "      <functions title=\"\"/>\n"
           "      <variables title=\"\"/>\n"
           "      <membergroups visible=\"yes\"/>\n"
           "    </memberdecl>\n"
           "    <detaileddescription title=\"\"/>\n"
           "    <memberdef>\n"
           "      <inlineclasses title=\"\"/>\n"
           "      <defines title=\"\"/>\n"
           "      <typedefs title=\"\"/>\n"
           "      <enums title=\"\"/>\n"
           "      <functions title=\"\"/>\n"
           "      <variables title=\"\"/>\n"
           "    </memberdef>\n"
           "    <authorsection/>\n"
           "  </file>\n\n"
           "  <group>\n"
           "    <briefdescription visible=\"yes\"/>\n"
           "    <groupgraph visible=\"$GROUP_GRAPHS\"/>\n"
           "    <memberdecl>\n"
           "      <nestedgroups visible=\"yes\" title=\"\"/>\n"
           "      <dirs visible=\"yes\" title=\"\"/>\n"
           "      <files visible=\"yes\" title=\"\"/>\n"
           "      <namespaces visible=\"yes\" title=\"\"/>\n"
           "      <classes visible=\"yes\" title=\"\"/>\n"
           "      <defines title=\"\"/>\n"
           "      <typedefs title=\"\"/>\n"
           "      <enums title=\"\"/>\n"
           "      <enumvalues title=\"\"/>\n"
           "      <functions title=\"\"/>\n"
           "      <variables title=\"\"/>\n"
           "      <signals title=\"\"/>\n"
           "      <publicslots title=\"\"/>\n"
           "      <protectedslots title=\"\"/>\n"
           "      <privateslots title=\"\"/>\n"
           "      <events title=\"\"/>\n"
           "      <properties title=\"\"/>\n"
           "      <friends title=\"\"/>\n"
           "      <membergroups visible=\"yes\"/>\n"
           "    </memberdecl>\n"
           "    <detaileddescription title=\"\"/>\n"
           "    <memberdef>\n"
           "      <pagedocs/>\n"
           "      <inlineclasses title=\"\"/>\n"
           "      <defines title=\"\"/>\n"
           "      <typedefs title=\"\"/>\n"
           "      <enums title=\"\"/>\n"
           "      <enumvalues title=\"\"/>\n"
           "      <functions title=\"\"/>\n"
           "      <variables title=\"\"/>\n"
           "      <signals title=\"\"/>\n"
           "      <publicslots title=\"\"/>\n"
           "      <protectedslots title=\"\"/>\n"
           "      <privateslots title=\"\"/>\n"
           "      <events title=\"\"/>\n"
           "      <properties title=\"\"/>\n"
           "      <friends title=\"\"/>\n"
           "    </memberdef>\n"
           "    <authorsection visible=\"yes\"/>\n"
           "  </group>\n\n"
           "  <directory>\n"
           "    <briefdescription visible=\"yes\"/>\n"
           "    <directorygraph visible=\"yes\"/>\n"
           "    <memberdecl>\n"
           "      <dirs visible=\"yes\"/>\n"
           "      <files visible=\"yes\"/>\n"
           "    </memberdecl>\n"
           "    <detaileddescription title=\"\"/>\n"
           "  </directory>\n"
           "</doxygenlayout>\n";
    return true;
}

bool Doxygen::writeConf()
{
    auto relPath = DocDirName + '/' + "doxygen.conf";
    auto filePath = bf::path(m_db.getRootPath()) / relPath;
    log::info() << "Generating " << relPath << std::endl;
    std::ofstream out(filePath.string());
    if (!out) {
        log::error() << "Failed to create " << filePath.string() << std::endl;
        return false;
    }

    auto& pkgName = m_db.getPackageName();
    auto dirName = pkgName;
    ba::replace_all(dirName, " ", "_");

    out << "DOXYFILE_ENCODING      = UTF-8\n"
           "PROJECT_NAME           = \"" << pkgName << "\"\n"
           "PROJECT_BRIEF          = \"Documentation for " << pkgName << " project.\"\n"
           "OUTPUT_DIRECTORY = /" << dirName << "\n"
           "BRIEF_MEMBER_DESC      = YES\n"
           "REPEAT_BRIEF           = YES\n"
           "ALWAYS_DETAILED_SEC    = NO\n"
           "INLINE_INHERITED_MEMB  = YES\n"
           "FULL_PATH_NAMES        = YES\n"
           "SHORT_NAMES            = NO\n"
           "INHERIT_DOCS           = YES\n"
           "SEPARATE_MEMBER_PAGES  = NO\n"
           "TAB_SIZE               = 4\n"
           "OPTIMIZE_OUTPUT_FOR_C  = NO\n"
           "OPTIMIZE_OUTPUT_JAVA   = NO\n"
           "OPTIMIZE_FOR_FORTRAN   = NO\n"
           "OPTIMIZE_OUTPUT_VHDL   = NO\n"
           "MARKDOWN_SUPPORT       = YES\n"
           "AUTOLINK_SUPPORT       = YES\n"
           "BUILTIN_STL_SUPPORT    = YES\n"
           "CPP_CLI_SUPPORT        = NO\n"
           "SIP_SUPPORT            = NO\n"
           "IDL_PROPERTY_SUPPORT   = YES\n"
           "DISTRIBUTE_GROUP_DOC   = NO\n"
           "GROUP_NESTED_COMPOUNDS = NO\n"
           "SUBGROUPING            = YES\n"
           "INLINE_GROUPED_CLASSES = NO\n"
           "INLINE_SIMPLE_STRUCTS  = NO\n"
           "TYPEDEF_HIDES_STRUCT   = NO\n"
           "LOOKUP_CACHE_SIZE      = 0\n"
           "EXTRACT_ALL            = NO\n"
           "EXTRACT_PRIVATE        = NO\n"
           "EXTRACT_PACKAGE        = NO\n"
           "EXTRACT_STATIC         = NO\n"
           "EXTRACT_LOCAL_CLASSES  = YES\n"
           "EXTRACT_LOCAL_METHODS  = NO\n"
           "EXTRACT_ANON_NSPACES   = NO\n"
           "HIDE_UNDOC_MEMBERS     = YES\n"
           "HIDE_UNDOC_CLASSES     = YES\n"
           "HIDE_FRIEND_COMPOUNDS  = NO\n"
           "HIDE_IN_BODY_DOCS      = NO\n"
           "INTERNAL_DOCS          = NO\n"
           "CASE_SENSE_NAMES       = YES\n"
           "HIDE_SCOPE_NAMES       = NO\n"
           "HIDE_COMPOUND_REFERENCE= NO\n"
           "SHOW_INCLUDE_FILES     = YES\n"
           "SHOW_GROUPED_MEMB_INC  = NO\n"
           "FORCE_LOCAL_INCLUDES   = YES\n"
           "INLINE_INFO            = NO\n"
           "SORT_MEMBER_DOCS       = YES\n"
           "SORT_BRIEF_DOCS        = NO\n"
           "SORT_MEMBERS_CTORS_1ST = YES\n"
           "SORT_GROUP_NAMES       = NO\n"
           "SORT_BY_SCOPE_NAME     = YES\n"
           "STRICT_PROTO_MATCHING  = NO\n"
           "GENERATE_TODOLIST      = YES\n"
           "GENERATE_TESTLIST      = YES\n"
           "GENERATE_BUGLIST       = YES\n"
           "GENERATE_DEPRECATEDLIST= YES\n"
           "MAX_INITIALIZER_LINES  = 30\n"
           "SHOW_USED_FILES        = YES\n"
           "SHOW_FILES             = YES\n"
           "SHOW_NAMESPACES        = YES\n"
           "LAYOUT_FILE            = doc/layout.xml\n"
           "QUIET                  = YES\n"
           "WARNINGS               = YES\n"
           "WARN_IF_UNDOCUMENTED   = NO\n"
           "WARN_IF_DOC_ERROR      = YES\n"
           "WARN_NO_PARAMDOC       = YES\n"
           "WARN_AS_ERROR          = YES\n"
           "WARN_FORMAT            = \"$file:$line: $text\"\n"
           "INPUT_ENCODING         = UTF-8\n"
           "RECURSIVE              = YES\n"
           "EXCLUDE                = cc_plugin\n"
           "EXCLUDE_SYMLINKS       = NO\n"
           "EXCLUDE_PATTERNS       = */cc_plugin/* */install/*\n"
           "EXCLUDE_SYMBOLS        = *details *cc_plugin\n"
           "EXAMPLE_RECURSIVE      = NO\n"
           "FILTER_SOURCE_FILES    = NO\n"
           "SOURCE_BROWSER         = NO\n"
           "INLINE_SOURCES         = NO\n"
           "STRIP_CODE_COMMENTS    = YES\n"
           "REFERENCED_BY_RELATION = NO\n"
           "REFERENCES_RELATION    = NO\n"
           "REFERENCES_LINK_SOURCE = YES\n"
           "SOURCE_TOOLTIPS        = YES\n"
           "USE_HTAGS              = NO\n"
           "VERBATIM_HEADERS       = YES\n"
           "CLANG_ASSISTED_PARSING = NO\n"
           "CLANG_OPTIONS          =\n"
           "ALPHABETICAL_INDEX     = YES\n"
           "COLS_IN_ALPHA_INDEX    = 5\n"
           "GENERATE_HTML          = YES\n"
           "HTML_OUTPUT            = html\n"
           "HTML_FILE_EXTENSION    = .html\n"
           "HTML_COLORSTYLE_HUE    = 220\n"
           "HTML_COLORSTYLE_SAT    = 100\n"
           "HTML_COLORSTYLE_GAMMA  = 80\n"
           "HTML_TIMESTAMP         = YES\n"
           "HTML_DYNAMIC_SECTIONS  = NO\n"
           "HTML_INDEX_NUM_ENTRIES = 100\n"
           "GENERATE_DOCSET        = NO\n"
           "GENERATE_HTMLHELP      = NO\n"
           "GENERATE_QHP           = NO\n"
           "GENERATE_ECLIPSEHELP   = NO\n"
           "DISABLE_INDEX          = NO\n"
           "GENERATE_TREEVIEW      = NO\n"
           "ENUM_VALUES_PER_LINE   = 4\n"
           "TREEVIEW_WIDTH         = 250\n"
           "EXT_LINKS_IN_WINDOW    = NO\n"
           "FORMULA_FONTSIZE       = 10\n"
           "FORMULA_TRANSPARENT    = YES\n"
           "USE_MATHJAX            = NO\n"
           "SEARCHENGINE           = NO\n"
           "SERVER_BASED_SEARCH    = NO\n"
           "EXTERNAL_SEARCH        = NO\n"
           "SEARCHDATA_FILE        = searchdata.xml\n"
           "GENERATE_LATEX         = NO\n"
           "GENERATE_RTF           = NO\n"
           "GENERATE_MAN           = NO\n"
           "GENERATE_XML           = NO\n"
           "GENERATE_DOCBOOK       = NO\n"
           "GENERATE_AUTOGEN_DEF   = NO\n"
           "GENERATE_PERLMOD       = NO\n"
           "ENABLE_PREPROCESSING   = YES\n"
           "MACRO_EXPANSION        = NO\n"
           "EXPAND_ONLY_PREDEF     = NO\n"
           "SEARCH_INCLUDES        = YES\n"
           "PREDEFINED             = FOR_DOXYGEN_DOC_ONLY\n"
           "SKIP_FUNCTION_MACROS   = YES\n"
           "ALLEXTERNALS           = NO\n"
           "EXTERNAL_GROUPS        = YES\n"
           "EXTERNAL_PAGES         = YES\n"
           "PERL_PATH              = /usr/bin/perl\n"
           "CLASS_DIAGRAMS         = YES\n"
           "HIDE_UNDOC_RELATIONS   = YES\n"
           "HAVE_DOT               = NO\n";

    return true;
}

bool Doxygen::writeNamespaces()
{
    auto& ns = m_db.getProtocolNamespace();
    auto nsFile = ns + ".dox";
    if (ns.empty()) {
        nsFile = "namespaces" + nsFile;
    }

    auto relPath = DocDirName + '/' + nsFile;
    auto filePath = bf::path(m_db.getRootPath()) / relPath;
    log::info() << "Generating " << relPath << std::endl;
    std::ofstream out(filePath.string());
    if (!out) {
        log::error() << "Failed to create " << filePath.string() << std::endl;
        return false;
    }

    if (!ns.empty()) {
        out << "/// \\namespace " << ns << "\n"
               "/// \\brief Main namespace for all classes / functions of this protocol library.\n\n";
    }

    out << "/// \\namespace " << common::scopeFor(ns, common::messageNamespaceNameStr()) << "\n"
           "/// \\brief Namespace for all the messages defined in this protocol.\n\n"
           "/// \\namespace " << common::scopeFor(ns, common::fieldNamespaceNameStr()) << "\n"
           "/// \\brief Namespace for all the stand alone fields defined in this protocol.\n\n"
           "/// \\namespace " << common::scopeFor(ns, common::builtinNamespaceNameStr()) << "\n"
           "/// \\brief Namespace for all implicitly defined (built-in) fields.\n\n";
    return true;
}

bool Doxygen::writeMain()
{
    auto relPath = DocDirName + "/main.dox";
    auto filePath = bf::path(m_db.getRootPath()) / relPath;
    log::info() << "Generating " << relPath << std::endl;
    std::ofstream out(filePath.string());
    if (!out) {
        log::error() << "Failed to create " << filePath.string() << std::endl;
        return false;
    }

    auto& ns = m_db.getProtocolNamespace();
    auto interfaceType = common::scopeFor(ns, common::msgInterfaceStr());
    auto idType = common::scopeFor(ns, common::msgIdEnumName());
    std::string endian("comms::traits::endian::Little");
    if (ba::ends_with(m_db.getEndian(), "BigEndian")) {
        ba::replace_all(endian, "Little", "Big");
    }

    out << "/// \\mainpage " << m_db.getPackageName() << " Binary Protocol\n"
           "/// \\tableofcontents\n"
           "/// This library implements \"" << m_db.getPackageName() << "\" binary protocol in terms of\n"
           "/// <a href=\"\">COMMS Library</a>.\n"
           "/// It is highly recommended to have documentation of the latter also opened and used for reference\n"
           "/// In order to fully understand this tutorial.\n"
           "/// \n"
           "/// \\section main_page_interface Interface Class\n"
           "/// The main philosophy of the \\b COMMS library is to have single \n"
           "/// implementation of the messages and fields in the binary protocol, while\n"
           "/// allowing the application being developed to configure polymorphic interfaces\n"
           "/// as well as data types for some critical fields.\n"
           "///\n"
           "/// The basic interface class is defined to be \\ref " << interfaceType << ". It defines\n"
           "/// the protocol endian as well as internal message id type (\\ref " << idType << ").\n"
           "/// \\code\n"
           "/// class " << interfaceType << "\n"
           "/// {\n"
           "///     // Define endian type tag\n"
           "///     using Endian = " << endian << ";\n"
           "///\n"
           "///     // Define type of the message ID\n"
           "///     using MsdIdType = " << idType << ";\n"
           "///\n"
           "///     // Define type of the message ID when used as function parameter\n"
           "///     using MsgIdParamType = " << idType << ";\n"
           "///\n"
           "///     // Set the blockLength value (used by transport framing)\n"
           "///     void setBlockLength(std::size_t value);\n"
           "///\n"
           "///     // Get the blockLength value\n"
           "///     std::size_t getBlockLength() const;\n"
           "///\n"
           "///     // Set the version value\n"
           "///     void setVersion(unsigned value);\n"
           "///\n"
           "///     // Get the version value\n"
           "///     unsigned getVersion() const;\n"
           "/// };\n"
           "/// \\endcode\n"
           "/// This basic interface does \\b NOT define any virtual functions. However,\n"
           "/// it may be extended using various options from \\b comms::option namespace.\n"
           "/// Below is basic guide and examples on available options. For more details please\n"
           "/// read the <b>\"Messages Tutorial\"</b> page of the \\b COMMS library documentation.\n"
           "///\n"
           "/// \\subsection main_page_interface_read Polymorphic Read\n"
           "/// In order to introduce polymorphic read functionality, provide type of\n"
           "/// read iterator using \\b comms::option::ReadIterator option.\n"
           "/// \\code\n"
           "/// using MyInterface = \n"
           "///     " << interfaceType << "<\n"
           "///         comms::option::ReadIterator<const std::uint8_t*>\n"
           "///     >;\n"
           "/// \\endcode\n"
           "/// The code is equivalent to having the following member types and functions:\n"
           "/// \\code\n"
           "/// class MyInterface\n"
           "/// {\n"
           "/// public:\n"
           "///     // Iterator used for reading\n"
           "///     using ReadIterator = const std::uint8_t*;\n"
           "///\n"
           "///     // Read operation (using NVI idiom)\n"
           "///     comms::ErrorStatus read(ReadIterator& iter, std::size_t len)\n"
           "///     {\n"
           "///         return readImpl(iter, len);\n"
           "///     }\n"
           "///\n"
           "/// protected:\n"
           "///     // Polymorphic read implemented in actual message class\n"
           "///     virtual comms::ErrorStatus readImpl(ReadIterator& iter, std::size_t len) = 0;\n"
           "/// };\n"
           "/// \\endcode\n"
           "///\n"
           "/// \\subsection main_page_interface_write Polymorphic Write\n"
           "/// In order to introduce polymorphic write functionality, provide type of\n"
           "/// write iterator using \\b comms::option::WriteIterator option.\n"
           "/// \\code\n"
           "/// using MyInterface =\n"
           "///     " << interfaceType << "<\n"
           "///         comms::option::WriteIterator<std::uint8_t*>\n"
           "///     >;\n"
           "/// \\endcode\n"
           "/// The code is equivalent to having the following member types and functions:\n"
           "/// \\code\n"
           "/// class MyInterface\n"
           "/// {\n"
           "/// public:\n"
           "///     // Iterator used for writing\n"
           "///     using WriteIterator = std::uint8_t*;\n"
           "///\n"
           "///     // Write operation (using NVI idiom)\n"
           "///     comms::ErrorStatus write(WriteIterator& iter, std::size_t len) const\n"
           "///     {\n"
           "///         return writeImpl(iter, len);\n"
           "///     }\n"
           "///\n"
           "/// protected:\n"
           "///     // Polymorphic write implemented in actual message class\n"
           "///     virtual comms::ErrorStatus writeImpl(WriteIterator& iter, std::size_t len) const = 0;\n"
           "/// };\n"
           "/// \\endcode\n"
           "///\n"
           "/// \\subsection main_page_interface_length Polymorphic Serialisation Length Retrieval\n"
           "/// In order to introduce polymorphic serialisation length retrieval functionality, \n"
           "/// pass \\b comms::option::LengthInfoInterface option to the \\ref " << interfaceType << "\n"
           "/// interface class.\n"
           "/// \\code\n"
           "/// using MyInterface = \n"
           "///     " << interfaceType << "<\n"
           "///         comms::option::LengthInfoInterface\n"
           "///     >;\n"
           "/// \\endcode\n"
           "/// The code is equivalent to having the following member functions:\n"
           "/// \\code\n"
           "/// class MyInterface\n"
           "/// {\n"
           "/// public:\n"
           "///     // Length retrieval operation (using NVI idiom)\n"
           "///     std::size_t length() const\n"
           "///     {\n"
           "///         return lengthImpl();\n"
           "///     }\n"
           "/// \n"
           "/// protected:\n"
           "///     // Polymorphic length retrieval implemented in actual message class\n"
           "///     virtual std::size_t lengthImpl() const = 0;\n"
           "/// };\n"
           "/// \\endcode\n"
           "///\n"
           "/// \\subsection main_page_interface_id Polymorphic Message ID Retrieval\n"
           "/// In order to introduce polymorphic message ID retrieval functionality,\n"
           "/// pass \\b comms::option::IdInfoInterface option to the \\ref " << interfaceType << "\n"
           "/// interface class.\n"
           "/// \\code\n"
           "/// using MyInterface =\n"
           "///     " << interfaceType << "<\n"
           "///         comms::option::IdInfoInterface\n"
           "///     >;\n"
           "/// \\endcode\n"
           "/// The code is equivalent to having the following member functions:\n"
           "/// \\code\n"
           "/// class MyInterface\n"
           "/// {\n"
           "/// public:\n"
           "///     // ID retrieval operation (using NVI idiom)\n"
           "///     MsgIdParamType getId() const\n"
           "///     {\n"
           "///         return getIdImpl();\n"
           "///     }\n"
           "///\n"
           "/// protected:\n"
           "///     // Polymorphic id retrieval implemented in actual message class\n"
           "///     virtual MsgIdParamType getIdImpl() const = 0;\n"
           "/// };\n"
           "/// \\endcode\n"
           "///\n"
           "/// \\subsection main_page_interface_valid Polymorphic Validity Check\n"
           "/// The SBE schemas allow limiting range of valid values for some fields.\n"
           "/// The message is considered to be valid if all of its fields are valid.\n"
           "/// In order to introduce polymorphic message validity check functionality, \n"
           "/// pass \\b comms::option::ValidCheckInterface option to the \\ref " << interfaceType <<"\n"
           "/// interface class.\n"
           "/// \\code\n"
           "/// using MyInterface = \n"
           "///     " << interfaceType << "<\n"
           "///         comms::option::ValidCheckInterface\n"
           "///     >;\n"
           "/// \\endcode\n"
           "/// The code is equivalent to having the following member functions:\n"
           "/// \\code\n"
           "/// class MyInterface\n"
           "/// {\n"
           "/// public:\n"
           "///     // Validity check operation (using NVI idiom)\n"
           "///     bool valid() const\n"
           "///     {\n"
           "///         return validImpl();\n"
           "///     }\n"
           "/// \n"
           "/// protected:\n"
           "///     // Polymorphic validity check implemented in actual message class\n"
           "///     virtual bool validImpl() const = 0;\n"
           "/// };\n"
           "/// \\endcode\n"
           "///\n"
           "/// \\subsection main_page_interface_dispatch Polymorphic Dispatch to Handling\n"
           "/// In order to introduce polymorphic dispatch of the message to its handling function,\n"
           "/// provide the type of your handling object using \\b comms::option::Handler option.\n"
           "/// Please refer to \\ref main_page_handling section for details on the required interface\n"
           "/// of the handling object type.\n"
           "/// \\code\n"
           "/// using MyInterface =\n"
           "///     " << interfaceType << "<\n"
           "///         comms::option::Handler<MyHandler>\n"
           "///     >;\n"
           "/// \\endcode\n"
           "/// The code is equivalent to having the following type and member functions:\n"
           "/// \\code\n"
           "/// class MyInterface\n"
           "/// {\n"
           "/// public:\n"
           "///     // Redefinition of the handler type\n"
           "///     using Handler = MyHandler;\n"
           "///\n"
           "///     // Dispatch to handling operation (using NVI idiom)\n"
           "///     void dispatch(MyHandler& handler) const\n"
           "///     {\n"
           "///         dispatchImpl(handler);\n"
           "///     }\n"
           "///\n"
           "/// protected:\n"
           "///     // Polymorphic dispatch to handling implemented in actual message class\n"
           "///     virtual void dispatchImpl() const = 0;\n"
           "/// };\n"
           "/// \\endcode\n"
           "/// \\b NOTE, that \\b dispatch() member function may return a value (handling status), please\n"
           "/// refer to \\ref main_page_handling section for details.\n"
           "///\n"
           "/// \\subsection main_page_interface_refresh Polymorphic Refresh\n"
           "/// This library allows manual update of the message object contents, such as\n"
           "/// updating the version of the message. Such an update, may result the message\n"
           "/// object being in an invalid state, where some fields are marked to exist and will be\n"
           "/// serialised in write operation, when they should not be according to the new\n"
           "/// version value. The \\b COMMS library provides a @b refresh() interface member function\n"
           "/// for such cases. It can be enabled by using \\b comms::option::RefreshInterface\n"
           "/// option.\n"
           "/// \\code\n"
           "/// using MyInterface =\n"
           "///     " << interfaceType << "<\n"
           "///         comms::option::RefreshInterface\n"
           "///     >;\n"
           "/// \\endcode\n"
           "/// The code is equivalent to having the following member functions:\n"
           "/// \\code\n"
           "/// class MyInterface\n"
           "/// {\n"
           "/// public:\n"
           "///     // Refresh operation (using NVI idiom)\n"
           "///     bool refresh()\n"
           "///     {\n"
           "///         return refreshImpl();\n"
           "///     }\n"
           "///\n"
           "/// protected:\n"
           "///     // Polymorphic refresh implemented in actual message class\n"
           "///     virtual void refreshImpl() const = 0;\n"
           "/// };\n"
           "/// \\endcode\n"
           "/// \\b NOTE, that \\b refresh() member function returns \\b true if\n"
           "/// <b>at least</b> one of the inner fields has been updated, and \\b false\n"
           "/// if message contents haven't been changed. Also note, that the message\n"
           "/// contents are updated (marked as exsiting or missing) according the\n"
           "/// version information, not the vice versa.\n"
           "///\n"
           "/// Below is an example on updating the version via common interface class:\n"
           "/// \\code\n"
           "/// bool updateVersion(MyMessage& msg, unsigned version)\n"
           "/// {\n"
           "///     msg.setVersion(version);\n"
           "///     return msg.refresh();\n"
           "/// }\n"
           "/// \\endcode\n"
           "///\n"
           "/// \\subsection main_page_interface_meta Meta-Programming\n"
           "/// The \\b comms::Message class (extended by \\ref " << interfaceType << ") from the \n"
           "/// \\b COMMS library defines multiple\n"
           "/// \\b constexpr static functions to allow compile time analysis of\n"
           "/// the supported interface. The \\ref " << interfaceType << " class inherits all this functions\n"
           "/// \\code\n"
           "/// namespace " << ns << "\n"
           "/// {\n"
           "///\n"
           "/// template <typename... TOpt>\n"
           "/// class Message : public\n"
           "///     comms::Message<\n"
           "///         ...,\n"
           "///         TOpt...\n"
           "///     >\n"
           "/// {\n"
           "/// public:\n"
           "///     // Check whether polymorphic read is supported\n"
           "///     static consexpr bool hasRead();\n"
           "/// \n"
           "///     // Check whether polymorphic write is supported\n"
           "///     static consexpr bool hasWrite();\n"
           "///\n"
           "///     // Check whether polymorphic length calculation is supported\n"
           "///     static consexpr bool hasLength();\n"
           "///\n"
           "///     // Check whether polymorphic message ID retrieval is supported\n"
           "///     static constexpr bool hasGetLength();\n"
           "///\n"
           "///     // Check whether polymorphic validity check is supported\n"
           "///     static constexpr bool hasValid();\n"
           "///\n"
           "///     // Check whether polymorphic dispatch is supported\n"
           "///     static constexpr bool hasDispatch();\n"
           "///\n"
           "///     // Check whether polymorphic refresh is supported\n"
           "///     static constexpr bool hasRefresh();\n"
           "/// };\n"
           "///\n"
           "/// } // namespace " << ns << "\n"
           "/// \\endcode\n"
           "/// These functions may be used at compile time to determine the supported\n"
           "/// interface if needed.\n"
           "/// \n"
           "/// \\subsection main_page_interface_input_output Input / Output Interfaces\n"
           "/// Some protocols may use uni-directional messages, i.e. some messages only\n"
           "/// sent but never received, or only received, but never sent. In this case,\n"
           "/// input messages may require polymorphic read, but do not require polymorphic\n"
           "/// write. The output messages, on the other hand, will require support for\n"
           "/// polymorphic write, but do not need support for read. If this is the case,\n"
           "/// then it is recommended to split the common interface class into two separate\n"
           "/// ones. For example:\n"
           "/// \\code\n"
           "/// // Interface for input messages\n"
           "/// using MyIntputMessage = \n"
           "///     " << interfaceType << "ns::Message<\n"
           "///         comms::option::ReadIterator<const std::uint8*>, // support for read\n"
           "///         comms::option::Handler<MyHandler> // support for dispatch\n"
           "///     >;\n"
           "///\n"
           "/// // Interface for output messages\n"
           "/// using MyOutputMessage =\n"
           "///     " << interfaceType << "<\n"
           "///         comms::option::WriteIterator<std::uint8_t*>, // support for polymorphic write\n"
           "///         comms::option::IdInfoInterface, // Support for polymorphic id retrieval\n"
           "///         comms::option::LengthInfoInterface // Support for polymorphic output buffer length calculation\n"
           "///     >;\n"
           "/// \\endcode\n"
           "/// These classes may be passed as the first template parameter to all the\n"
           "/// protocol message definition classes. See \\ref main_page_protocol_messages\n"
           "/// section below for more details.\n"
           "/// \\section main_page_protocol_messages Protocol Messages\n"
           "/// TODO\n"
           "/// \\section main_page_handling Handling the Message\n"
           "/// TODO\n"
           "/// \\section main_page_fields Fields\n"
           "/// TODO\n"
           "/// \\section main_page_transport Transport Frame\n"
           "/// TODO\n"
           "///\n\n";
    return true;
}




} // namespace sbe2comms
